### PR TITLE
Update New PolicyIDs Dystoblock

### PR DESCRIPTION
**Pull request by Dystoblock**
@CNFT-io
Update Drop 3 on CNFT

Thank you

### CODE REVIEW

**Comment by CNFT-io** [comment]
What is going on? Do you need this added as you keep closing it?

**Comment by Dystoblock** [comment]
I'm not doing it right, it's too much, or it's right. I will open it again Thank you

**Comment by Dystoblock** [comment]
I think it didn't reach you. I'm sorry.

**Comment by Dystoblock** [comment]
I updated the last policy of the project this year. Thank you very much.

**Comment by Dystoblock** [comment]
Verify please!!

**Pull request closed without merging**
